config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/main', to: 'pages#main', as: :pages
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :profiles, except: [:delete, :index, :new]
  resources :accounts, except: [:show]
  resources :branches
  resources :salesmen
  resources :users, except: [:new]
  resources :customers
  resources :suppliers
  resources :warehouses
  resources :product_settings, except: [:show]
  resources :products, except: [:show]
  resources :assetms
  resources :journals
  resources :stocks
end

app/models/branch.rb
class Branch < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    has_many :accounts, inverse_of: :branch
    has_many :stocks, inverse_of: :branch
    has_many :inventories, inverse_of: :branch
    has_many :salesmen, inverse_of: :branch
    has_many :assetms, inverse_of: :branch
    has_many :suppliers, inverse_of: :branch
    has_many :customers, inverse_of: :branch
    has_many :journals, inverse_of: :branch
    has_many :users, inverse_of: :branch
    has_many :groups, inverse_of: :branch
    has_many :inventories, inverse_of: :branch
    has_many :product_settings, inverse_of: :branch
    has_many :products, inverse_of: :branch
    has_many :transaction_logs, inverse_of: :branch
    has_many :warehouses, inverse_of: :branch
    validates :code, uniqueness: true
    validates :name, uniqueness: true
    
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
    #before_action :require_login
    before_action :find_branch, only:[:edit, :destroy, :show, :update]
    
    def show
       
    end
    
    def edit
        
    end
    
    def new
        @branch = Branch.new
    end
    
    def create
        @branch = Branch.new(branch_params)
        if @branch.save
            flash[:success] = "Branch data created successfully!"
            redirect_to branches_path
        else
            render 'new'
        end
    end
    
    def destroy
        @branch.destroy
        flash[:warning] = "Branch data deleted successfully!"
        redirect_to branches_path
    end
    
    def update
        if @branch.update(branch_params)
            flash[:success] = "Branch data updated successfully!"
            redirect_to branches_path
        else
            render 'edit'
        end
    end
    
    def index
        @branches= Branch.all
    end
    
    private
    
    def find_branch
        @branch = Branch.friendly.find(params[:id])
    end
    
    def branch_params
        params.require(:branch).permit(:code, :name, :region, :city, 
        :address, :telp, :cp, :description, :slug )
    end
   
end

app/views/branches/_form.html.erb
        <%= render 'shared/errors', obj: @branch %>
        <div class="row">
            <%= form_for @branch do |f|  %>
            
                <div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :code %><%= f.text_field :code, :class => "form-control" %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :name %><%= f.text_field :name, :class => "form-control" %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :region %><%= f.text_field :region, :class => "form-control"  %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :city %><%= f.text_field :city, :class => "form-control"  %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :address %><%= f.text_field :address, :class => "form-control"  %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :telp %><%= f.text_field :telp, :class => "form-control"  %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :cp %><%= f.text_field :cp, :class => "form-control" %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.label :description %><%= f.text_area :description, :class => "form-control" %>
            		</div>
            	</div>
            	<br>
            	<div class="col-sm-12">
            		<%= link_to raw("<i class=\"fa fa-times\" aria-hidden=\"true\"></i> Cancel"), branches_path , :class => "btn btn-danger btn-flat" %> 
            		<%= button_tag( :class => "btn btn-success btn-flat") do %>
        			  <i class="fa fa-check" aria-hidden="true"></i> Submit 
        			<% end %>
            	</div>
            <%end %>
        </div>

app/views/branches/edit.html.erb
		<section class="content-header">
			<h1>Branch<small>Edit</small></h1>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Branch</a>
				</li>
				<li class="active">Edit Branch</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<!-- Default box -->
			<%flash.each do |name, msg| %>
			<div class="box box-danger box-solid" id="success-alert">
				<button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
				<h4><i class="icon fa fa-check"></i> Success</h4>
				<ul>
					<li><%= msg %></li>
				</ul>
			</div><%end %>
			<div class="box box-danger">
				<div class="box-header with-border">
					<h3 class="box-title">Edit Branch</h3>
				</div><!--content-->
				<div class="box-body">
					<%= render 'form' %>
				</div><!-- /.box-body -->
			</div><!-- /.box -->
		</section>

app/views/branches/index.html.erb
		<section class="content-header">
			<h1>Branches <small>List</small></h1>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Branches</a>
				</li>
				<li class="active">Index page</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<%= render 'shared/flash' %>
			
			<div class="box box-danger">
				<!-- /.box-header -->
				<div class="box-header">
		         <%= link_to "Create a Branch", new_branch_path, :class => "btn btn-primary btn-flat ", :rel => "tabs" %>
		        </div>
				<div class="box-body no-padding">
					<table class="table table-bordered">
						<tbody>
							<tr>
								<th style="width: 50px">Code</th>
								<th>Name</th>
								<th>Region</th>
								<th style="width: 140px">City</th>
								<th style="width: 80px">Telp</th>
								<th style="width: 170px">Contact</th>
								<th style="width: 170px">Update</th>
								<th style="width: 170px">Action</th>
							</tr>
							<tr><%@branches.each do |branch| %>
								<td><%= branch.code %></td>
								<td><%= branch.name %></td>
								<td><%= branch.region %></td>
								<td><%= branch.city %></td>
								<td><%= branch.telp %></td>
								<td><%= branch.cp %></td>
								<td><%= branch.updated_at %></td>
								<td><%= link_to "Show", branch_path(branch), :class => "btn btn-success btn-sm btn-flat", :rel => "tabs" %>
								<%= link_to "Edit", edit_branch_path(branch), :class => "btn btn-warning btn-sm btn-flat", :rel => "tabs" %> 
								<%= link_to "Delete",branch_path(branch), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger btn-sm btn-flat", :rel => "tabs" %></td>
							</tr><%end %>
						</tbody>
					</table>
				</div><!-- /.box-body -->
				<div class="box-footer no-padding">
					<p></p>
				</div>
			</div><!-- /.box-end -->
			
		</section>

app/views/branches/new.html.erb
		<section class="content-header">
			<h1>Branch <small>New</small></h1>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Branch</a>
				</li>
				<li class="active">New Branch</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<!-- Default box -->
			<%flash.each do |name, msg| %>
			<div class="alert alert-success alert-dismissible" id="success-alert">
				<button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
				<h4><i class="icon fa fa-check"></i> Success</h4>
				<ul>
					<li><%= msg %></li>
				</ul>
			</div><%end %>
			<div class="box box-primary box-solid">
				<div class="box-header with-border">
					<h3 class="box-title">New Branch</h3>
				</div><!--content-->
				<div class="box-body">
					<%= render 'form' %>
				</div><!-- /.box-body -->
			</div><!-- /.box -->
		</section>

app/views/branches/show.html.erb
        <section class="content">
        <% flash.each do |name, msg| %>
            <div class="alert alert-success alert-dismissible" id="success-alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i> Success</h4>
                <ul><li><%= msg %></li></ul>
             </div>
            <% end %>
        <h1>Show data</h1>
        <p> code = <%= @branch.code %></p>
        <p> name = <%= @branch.name %></p>
        <p> region = <%= @branch.region %></p>
        <p> city = <%= @branch.city %></p>
        <p> address = <%= @branch.address %></p>
        <p> telp = <%= @branch.telp %></p>
        <p> cp = <%= @branch.cp %></p>
        <p> description = <%= @branch.description %></p>
        <p> updated_at = <%= @branch.updated_at %></p>
        <p> created_at = <%= @branch.created_at %></p>
        <%= link_to raw("<i class=\"fa fa-arrow-left\" aria-hidden=\"true\"></i> Back"), branches_path , :class => "btn btn-primary btn-flat" %> 
        </section>