config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/main', to: 'pages#main', as: :pages
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :profiles, except: [:delete, :index, :new]
  resources :accounts, except: [:show]
  resources :branches
  resources :salesmen
  resources :users, except: [:new]
  resources :customers
  resources :suppliers
  resources :warehouses
  resources :product_settings, except: [:show]
  resources :products, except: [:show]
  resources :assetms
  resources :journals
  resources :stocks
end

app/models/product_setting.rb
class ProductSetting < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    validates :code, presence: true, length: {minimim: 1, maximum: 10}
    validates :product_type, presence: true
    validates :branch_id, presence: true
    belongs_to :branch, inverse_of: :product_settings
end

app/controllers/product_settings_controller.rb
class ProductSettingsController < ApplicationController
    before_action :require_login
    before_action :find_product_setting, only:[:edit, :destroy, :show, :update]
    before_action :require_same_branch, only:[:edit, :destroy, :show, :update]
    
    def edit
       
    end
    
    def new
        @product_setting = ProductSetting.new
    end
    
    def create
        @product_setting = ProductSetting.new(product_setting_params)
        @product_setting.branch = current_branch
    
        if @product_setting.save
            flash[:success] = "Product Setting data created successfully!"
            redirect_to product_settings_path
        else
            render 'new'
        end
    end
    
    def destroy
        @product_setting.destroy
        flash[:warning] = "Product Setting data deleted successfully!"
        redirect_to product_settings_path
    end
    
    def update
        if @product_setting.update(product_setting_params)
            flash[:success] = "Product Setting data updated successfully!"
            redirect_to product_settings_path
        else
            render 'edit'
        end
    end
    
    def index
        @product_settings= ProductSetting.all
    end
    
    private
    
    def find_product_setting
        @product_setting = ProductSetting.friendly.find(params[:id])
    end
    
    def product_setting_params
        params.require(:product_setting).permit(:code, :name, :product_type, :branch_id, current_user.branch_id, :slug)
    end
    
    def require_same_branch
        if current_user.branch_id != @product_setting.branch_id
            flash[:error]  = "You dont have permision for this action!"
            redirect_to product_settings_path
        end
    end
end

app/views/product_settings/_form.html.erb
        <%= render 'shared/errors', obj: @product_setting %>
        
        
        <div class="row">
            <%= simple_form_for @product_setting do |f|  %>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.input :code, hint: false,:error => false %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.input :name, hint: false,:error => false %>
            		</div>
            	</div>
            	<div class="col-sm-6">
            		<div class="form-group">
            			<%= f.input :product_type, 
            			    :collection => [['Product Brand','Brand'],['Product Size','Size'],['Product Motif','Motif'],['Product Type','Type'],['Product Density','Density'],['Product Color','Color'],['Product Quality','Quality']],
            			    as: :radio_buttons %>
            		</div>
            	</div>

            	<div class="col-sm-12">
                	<div class="text-right btn-toolbar">
                		<%= link_to raw("<i class=\"fa fa-times\" aria-hidden=\"true\"></i> Cancel"), product_settings_path , :class => "btn btn-danger btn-flat pull-right" %> 
                		<%= button_tag( :class => "btn btn-success btn-flat pull-right") do %>
            			  <i class="fa fa-check" aria-hidden="true"></i> Submit 
            			<% end %>
                	</div>
            	</div>
            <%end %>
        </div>

app/views/product_settings/edit.html.erb
		<section class="content-header">
			<h1>Product Setting <small>Edit</small></h1>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Product Setting</a>
				</li>
				<li class="active">Edit Product Setting</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<!-- Default box -->
			<div class="row">
			<div class="col-sm-6">
				<div class="box box-primary box-solid">
					<div class="box-header with-border">
						<h3 class="box-title">Edit Product Setting</h3>
					</div><!--content-->
					<div class="box-body">
						<%= render 'form' %>
					</div><!-- /.box-body -->
				</div><!-- /.box -->
			</div>
			</div>
		</section>

app/views/product_settings/index.html.erb
		<section class="content-header">
			 <%= link_to raw("<i class=\"fa fa-plus\" aria-hidden=\"true\"> </i> Create New Product Setting"), new_product_setting_path, :class => "btn btn-primary btn-flat "%>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Product Settings</a>
				</li>
				<li class="active">Index page</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<%= render 'shared/flash' %>
			
			<div class="box">
				<!-- /.box-header -->
				<div class="box-header adminheader">
	            	<h3 class="box-title">Product Settings </h3> <small>List</small>
	            </div>
				<div class="box-body padding-xs">
					<table id="dttable" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>Code</th>
								<th>Name</th>
								<th>Type</th>
								<th style="width: 80px">Action</th>
							</tr>
							</thead>
							</tbody>
							<tr><%@product_settings.each do |product_setting| %>
								<td><%= product_setting.code %></td>
								<td><%= product_setting.name %></td>
								<td><span class="label <%= product_setting.product_type %>"><%= product_setting.product_type %></span></td>
								
								<td>
								<table>
								<tr><td>
								<%= link_to raw("<i class=\"fa fa-edit\" aria-hidden=\"true\"></i>"), edit_product_setting_path(product_setting), :class => "btn btn-warning btn-sm", :rel => "tabs" %> </td>
								<td><%= link_to raw("<i class=\"fa fa-gavel\" aria-hidden=\"true\"> </i>"), product_setting_path(product_setting), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger btn-sm", :rel => "tabs" %>
								</td></tr>
								</table>
							</tr><%end %>
						</tbody>
					</table>
				</div><!-- /.box-body -->
				
			</div><!-- /.box-end -->
			
		</section>

app/views/product_settings/new.html.erb
		<section class="content-header">
			<h1>Product Settings <small>New</small></h1>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Product Settings</a>
				</li>
				<li class="active">New Product Setting</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<!-- Default box -->
			<div class="row">
			<div class="col-sm-6">
				<div class="box box-primary box-solid">
					<div class="box-header with-border">
						<h3 class="box-title">New Product Setting</h3>
					</div><!--content-->
					<div class="box-body">
						<%= render 'form' %>
					</div><!-- /.box-body -->
				</div><!-- /.box -->
			</div>
			</div>
		</section>