config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/main', to: 'pages#main', as: :pages
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :profiles, except: [:delete, :index, :new]
  resources :accounts, except: [:show]
  resources :branches
  resources :salesmen
  resources :users, except: [:new]
  resources :customers
  resources :suppliers
  resources :warehouses
  resources :product_settings, except: [:show]
  resources :products, except: [:show]
  resources :assetms
  resources :journals
  resources :stocks
end

app/models/journal.rb
class Journal < ApplicationRecord
    
    def self.search(search)
      where("code LIKE ?", "%#{search}%")
    end

    extend FriendlyId
    friendly_id :code, use: :slugged
    
    has_many :ledgers, inverse_of: :journal, dependent: :destroy
    belongs_to :branch, inverse_of: :journals
    accepts_nested_attributes_for :ledgers, allow_destroy: true, reject_if: proc { |att| att['coa'].blank? }
    
    NON_VALIDATABLE_ATTRS = ["id", "created_at", "updated_at"]
    VALIDATABLE_ATTRS = Journal.attribute_names.reject{|attr| NON_VALIDATABLE_ATTRS.include?(attr)}
    validates_presence_of VALIDATABLE_ATTRS

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
    before_action :require_login
    before_action :find_journal, only:[:edit, :destroy, :show, :update]
    before_action :require_same_branch, only:[:edit, :destroy, :show, :update]
    
    def show
        @ledgers = @journal.ledgers
    end
    
    def edit
        @accounts = Account.where(branch_id: Branch.find(session[:branch_id]))
    end
    
    def new
        if last_journal = Journal.where(:branch_id => Branch.find(session[:branch_id])).last
            last_code_number = last_journal.code.scan(/\d+$/).first.to_i
            new_code_number = last_code_number + 1
        else
            new_code_number = 1
        end
        t = Time.now()
        @journal = Journal.new
        @accounts = Account.where(branch_id: Branch.find(session[:branch_id]))
        2.times { @journal.ledgers.build }
        @journal.code= "#{"AJP-"}#{t.strftime("%y/%m")}#{sprintf("-%04d", new_code_number)}"
        @journal.branch = Branch.find(session[:branch_id])
    end
    
    def create
        if last_journal = Journal.where(:branch_id => Branch.find(session[:branch_id])).last
            last_code_number = last_journal.code.scan(/\d+$/).first.to_i
            new_code_number = last_code_number + 1
        else
            new_code_number = 1
        end
        @journal = Journal.new(journal_params)
        @journal.branch = Branch.find(session[:branch_id])
        @journal.code= "#{"AJP"}#{sprintf("%05d", new_code_number)}"
        
        if @journal.save
            flash[:success] = "Journal data created successfully!"
            redirect_to journals_path
        else
            render 'new'
        end
    end
    
    def destroy
        @journal.destroy
        flash[:warning] = "Journal data deleted successfully!"
        redirect_to journals_path
    end
    
    def update
    if @journal.update(journal_params)
        flash[:success] = "Journal data updated successfully!"
        redirect_to journals_path
    else
        render 'edit'
    end
    
    end
    
    def index
        @journals= Journal.where(branch_id: current_branch)
        if params[:search]
            @journals = Journal.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 30)
        else
            @journals = Journal.where(branch_id: current_branch).order('created_at DESC').paginate(page: params[:page], per_page: 30)
        end
    end
    
    private
    
    def find_journal
        @journal = Journal.friendly.find(params[:id])
    end
    
    def journal_params
        params.require(:journal).permit(
            :code,
            :date, 
            :status, 
            :description,
            :total,
            :branch_id, 
            :slug,
            ledgers_attributes: Ledger.attribute_names.map(&:to_sym).push(:_destroy)
        )
        #params.require(:todo_list).permit(:name, tasks_attributes: Task.attribute_names.map(&:to_sym).push(:_destroy))
    end
    
    def require_same_branch
        if current_user.branch_id != @journal.branch_id
            flash[:error]  = "You dont have permision for this action!"
            redirect_to journals_path
        end
    end
   
end
    

app/views/journals/_form.html.erb
        <%= render 'shared/errors', obj: @journal %>
        <div class="row">
            
            <%= simple_form_for @journal do |f|  %>
                <div class="col-sm-3">
                    <div class="form-group">
                        <%= f.input :code, 
                            hint: false,
                            :error => false,
                            :readonly => true, 
                            input_html: {value: @journal.code }
                        %>
                    </div>
                </div>
            	<div class="col-sm-3">
                	<div class="form-group">
                        <%= f.input :status, 
                            hint: false,
                            :error => false,
                            :collection => [
                                ['Active','Active'],
                                ['Inactive','Inactive']], 
                            id: 'select' 
                        %>
                    </div>
                </div>
            	<div class="col-sm-3">
            		<div class="form-group">
            			<%= f.input :date, as: :string, hint: false, :error => false, :input_html => { :class => 'fdate' }  %>
            		</div>
            	</div>
            	
            	<div class="col-sm-3">
            		<div class="form-group">
            		<%= f.input :total, hint: false,:error => false, as: :string, 
            		    :input_html => {:class=> 'currency', :readonly => true, :id => 'total', value: number_with_precision(f.object.total, precision: 0)} %>
            		</div>
            	</div>
            	<div class="col-sm-12">
            		<div class="form-group">
            			<%= f.input :description, as: :text, hint: false,:error => false, :input_html => {:class=> ''} %>
            		</div>
            	</div>
                
            	
                <div class="col-sm-12">
                    <table  class='fields'>
                        <hr>
                    	<%= f.simple_fields_for :ledgers do |builder| %>
                    	    <%= render 'ledger', f: builder %>
                        <% end %>
                    </table>
                    
                    <div class="text-right btn-toolbar">
                        <%= link_to_add_row(raw(
                            "<i class=\"fa fa-plus\" aria-hidden=\"true\"> </i> Add Journal"), 
                            f, :ledgers, class: 'btn btn-primary btn-flat', :disabled => :true) %>
                        <%= link_to raw(
                            "<i class=\"fa fa-times\" aria-hidden=\"true\"></i> Cancel"), 
                            journals_path , :class => "btn btn-danger btn-flat pull-right" 
                         %> 
                		<%= button_tag( :class => "btn btn-success btn-flat pull-right ledgerbutton")  do %>
            			  <i class="fa fa-check" aria-hidden="true"></i> Submit 
            			<% end %>
        			</div>
            	</div>
            <%end %>
        </div>
        
        

app/views/journals/_ledger.html.erb
<tr class="ledger">
<td class="col-sm-5">
    <div class="form-group">
        <%= f.label :coa %>
        <%= f.select :coa, options_from_collection_for_select(@accounts, :code, :code_with_label, :selected => f.object.coa), {:include_blank => true}, id: 'select' %>
    </div>
</td>
<td class="col-sm-3"><%= f.input :note %></td>

<td class="col-sm-2">
<%= f.input :debit, as: :string, 
    :input_html => {:class=> 'currency price', :rel => 'price', value: number_with_precision(f.object.debit, precision: 0)} %>
</td>
<td class="col-sm-2">
<%= f.input :credit, as: :string, 
    :input_html => {:class=> 'currency pricec', :rel => 'pricec', value: number_with_precision(f.object.credit, precision: 0)} %>
</td>

<td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= button_tag( :class => "btn btn-warning pull-right", 
        'data-toggle' => 'confirmation', 
        'data-placement' => 'top', 
        'data-singleton' => 'true'
    ) do %>
	    <i class="fa fa-trash-o" aria-hidden="true"></i> 
	<% end %>
</td>
</div>

app/views/journals/index.html.erb
		<section class="content-header">
			<%= link_to raw("<i class=\"fa fa-plus\" aria-hidden=\"true\"> </i> Create New Journal"), new_journal_path, :class => "btn btn-primary btn-flat "%>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Journals</a>
				</li>
				<li class="active">Index page</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<%= render 'shared/flash' %>
			
			<div class="box box-primary">
				<!-- /.box-header -->
				<div class="box-header">
					
		        <h3  class="box-title">Journals <small>List</small></h3>
		        <div class="pull-right">
					<%= form_tag(journals_path, :method => "get", id: "search-form") do %>
						<table class="table-search">
							<tr>
								<td class="td-search"><b class="pull-right">Search:</b></td>
								<td class="td-search"><%= text_field_tag :search, params[:search], class: "form-control input-sm search-field" %></td>
							</tr>
						</table>
						<%= submit_tag "search", :style => "display: none;" %>
					<% end %>
				</div>
		        </div>
				<div class="box-body" id="dttable_filter">
				
					<table class="table table-bordered table-hover" >
						<thead class="thead"
							<tr>
								<th style="width: 100px">Code</th>
								<th style="width: 100px">Date</th>
								<th style="width: 70px">Status</th>
								<th>Description</th>
								<th style="width: 125px">Action</th>
							</tr>
						</thead>
						<tbody>
							<%@journals.each do |journal| %>
							<tr>
								<td><%= journal.code %></td>
								<td><%= journal.date %></td>
								<td><span class="label <%= journal.status %>"><%= journal.status %></span></td>
								<td><%= journal.description %></td>
								<td>
									<table>
									<tr><td><%= link_to raw("<i class=\"fa fa-print\" aria-hidden=\"true\"></i>"), journal_path(journal), :class => "btn btn-success btn-sm " %></td>
	                                <td><%= link_to raw("<i class=\"fa fa-edit\" aria-hidden=\"true\"></i>"), edit_journal_path(journal), :class => "btn btn-warning btn-sm" %> </td>
	                                <td><%= link_to raw("<i class=\"fa fa-gavel\" aria-hidden=\"true\"> </i>"), journal_path(journal), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger btn-sm" %></td>
	                                </tr>
	                                </table>
                                </td>
							</tr>	
							<%end %>
						</tbody>
					</table>
				

				</div><!-- /.box-body -->
				<div class="box-footer ">
				
				</div>

			</div><!-- /.box-end -->
			
		</section>
		

app/views/journals/new.html.erb
		<section class="content-header">
			<h1>Journals <small>New</small></h1>
			<ol class="breadcrumb">
				<li>
					<a href="#"><i class="fa fa-dashboard"></i> Home</a>
				</li>
				<li>
					<a href="#">Journals</a>
				</li>
				<li class="active">New Journal</li>
			</ol>
		</section><!-- Main content -->
		<section class="content">
			<!-- Default box -->
			<div class="row">
			<div class="col-sm-8">
				<div class="box box-primary box-solid">
					<div class="box-header with-border">
						<h3 class="box-title">New Journal</h3>
					</div><!--content-->
					<div class="box-body">
						<%= render 'form' %>
					</div><!-- /.box-body -->
				</div><!-- /.box -->
			</div>
			</div>
		</section>

app/views/journals/show.html.erb
  <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header"  onload="window.print();" >
        <script>window.onload = function() { window.print(); }</script>
      <h1>
        Customer
        <small><%= @customer.code %></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Customers</a></li>
        <li class="active">View</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <i class="fa fa-home"></i> <%= @customer.name %>
            <small class="pull-right"></small>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          <address>
            <%= @customer.code %><br>
            <strong><%= @customer.name %></strong><br>
            <strong>Contact : </strong><%= @customer.cp %><br>
           <strong> Phone : </strong><%= @customer.telp %>
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <address>
            <strong>Limit Customer</strong><br>
            <strong>Credit Limit :</strong> <%= number_to_currency( @customer.climit, precision: 0, unit: "")  %><br>
            <strong>Credit Limit :</strong> <%= number_to_currency( @customer.dlimit, precision: 0, unit: "")  %><br>
            <strong>Credit Limit (tolerance) : </strong> 
                    <%= number_to_currency( @customer.tclimit, precision: 0, unit: "")  %><br>
            <strong>Credit Limit (tolerance) :</strong> 
                    <%= number_to_currency( @customer.tdlimit, precision: 0, unit: "")  %><br>
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>Status : </b>
          <%= @customer.status %>
          </br>
          
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Address</th>
              <th>Region</th>
              <th>City</th>
              <th>Telp</th>
            </tr>
            </thead>
            <tbody>
            <% @customer.addresses.each do |addresses| %>   
            <tr>
              <td><%= addresses.name %></td>
              <td><%= addresses.address %></td>
              <td><%= addresses.region %></td>
              <td><%= addresses.city %></td>
              <td><%= addresses.telp %></td>
            </tr>
            <% end %>
            </tbody>
          </table>
          
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
          <a href="#" target="_blank" class="btn btn-primary btn-flat"><i class="fa fa-print"></i> Print</a>
          <%= link_to raw("<i class=\"fa fa-times\" aria-hidden=\"true\"></i> Cancel"), customers_path , :class => "btn btn-danger btn-flat pull-right" %> 
        </div>
      </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>