config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/main', to: 'pages#main', as: :pages
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :profiles, except: [:delete, :index, :new]
  resources :accounts, except: [:show]
  resources :branches
  resources :salesmen
  resources :users, except: [:new]
  resources :customers
  resources :suppliers
  resources :warehouses
  resources :product_settings, except: [:show]
  resources :products, except: [:show]
  resources :assetms
  resources :journals
  resources :stocks
end

app/views/layouts/partials/_controlbar.html.erb
			<aside class="control-sidebar control-sidebar-dark">
				<!-- Create the tabs -->
				<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
					<li class="active">
						<a data-toggle="tab" href="#control-sidebar-home-tab"><i class="fa fa-home"></i></a>
					</li>
					<li>
						<a data-toggle="tab" href="#control-sidebar-settings-tab"><i class="fa fa-gears"></i></a>
					</li>
				</ul><!-- Tab panes -->
				<div class="tab-content">
					<!-- Home tab content -->
					<div class="tab-pane active" id="control-sidebar-home-tab">
						<h3 class="control-sidebar-heading">Lorem ipsum.</h3>
						<ul class="control-sidebar-menu">
							<li>
								<a href="javascript:;"><i class="menu-icon fa fa-gears bg-red"></i>
								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Lorem ipsum.</h4>
									<p>Content Sample</p>
								</div></a>
							</li>
						</ul><!-- /.control-sidebar-menu -->
						<h3 class="control-sidebar-heading">Lorem ipsum.</h3>
						<ul class="control-sidebar-menu">
							<li>
								<a href="javascript:;">
								<h4 class="control-sidebar-subheading">Lorem ipsum. <span class="pull-right-container"><span class="label label-danger pull-right">70%</span></span></h4>
								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
								</div></a>
							</li>
						</ul><!-- /.control-sidebar-menu -->
					</div><!-- /.tab-pane -->
					<!-- Stats tab content -->
					<div class="tab-pane" id="control-sidebar-stats-tab">
						Lorem ipsum dolor.
					</div><!-- /.tab-pane -->
					<!-- Settings tab content -->
					<div class="tab-pane" id="control-sidebar-settings-tab">
						<form method="post">
							<h3 class="control-sidebar-heading">Lorem ipsum dolor.</h3>
							<div class="form-group">
								<label class="control-sidebar-subheading">Lorem ipsum dolor. <input checked class="pull-right" type="checkbox"></label>
								<p>Lorem ipsum dolor sit amet, consectetur.</p>
							</div><!-- /.form-group -->
						</form>
					</div><!-- /.tab-pane -->
				</div>
			</aside><!-- /.control-sidebar -->
			<!-- Add the sidebar's background. This div must be placed
			   immediately after the control sidebar -->
			<div class="control-sidebar-bg"></div>

app/views/layouts/partials/_footerbar.html.erb
			<footer class="main-footer no-print">
				<!-- To the right -->
				<div class="pull-right hidden-xs">
					Alpha Version
				</div><!-- Default to the left -->
				<strong>Copyright &copy; 2017 <a href="#">Company</a>.</strong> All rights reserved.
			</footer>

app/views/layouts/partials/_head.html.erb
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<title>Acurasoft</title>
<%= csrf_meta_tags %>
<%= render 'application/favicon' %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

app/views/layouts/partials/_headerbar.html.erb
			<header class="main-header">
				<!-- Logo -->
				 <a class="logo" href="<%= root_path %>">
				 <span class="logo-mini"><%= image_tag 'logo-min.png',width: '50px' %></span> <!-- logo for regular state and mobile devices -->
				 <span class="logo-lg"><%= image_tag 'logo-min.png',width: '50px' %><b>ACURA</b></span></a> <!-- Header Navbar -->
				<nav class="navbar navbar-static-top" role="navigation">
					<!-- Sidebar toggle button-->
					 <a class="sidebar-toggle" data-toggle="offcanvas" href="#" role="button"><span class="sr-only">Toggle navigation</span></a> <!-- Navbar Right Menu -->
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<!-- Messages: style can be found in dropdown.less-->
							<li class="dropdown messages-menu">
								<!-- Menu toggle button -->
								 <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-envelope-o"></i> <span class="label label-success">4</span></a>
								<ul class="dropdown-menu">
									<li class="header">You have 4 messages</li>
									<li>
										<!-- inner menu: contains the messages -->
										<ul class="menu">
											<li>
												<!-- start message -->
												 <a href="#">
												<div class="pull-left">
													<!-- User Image -->
													<i class="fa fa-fw fa-user"></i>
												</div><!-- Message title and timestamp -->
												<h4>Support Team <small><i class="fa fa-clock-o"></i> 5 mins</small></h4><!-- The message -->
												<p>Why not buy a new awesome theme?</p></a>
											</li><!-- end message -->
										</ul><!-- /.menu -->
									</li>
									<li class="footer">
										<a href="#">See All Messages</a>
									</li>
								</ul>
							</li><!-- /.messages-menu -->
							<!-- Notifications Menu -->
							<li class="dropdown notifications-menu">
								<!-- Menu toggle button -->
								 <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-bell-o"></i> <span class="label label-warning">10</span></a>
								<ul class="dropdown-menu">
									<li class="header">You have 10 notifications</li>
									<li>
										<!-- Inner Menu: contains the notifications -->
										<ul class="menu">
											<li>
												<!-- start notification -->
												 <a href="#"><i class="fa fa-users text-aqua"></i> 5 new members joined today</a>
											</li><!-- end notification -->
										</ul>
									</li>
									<li class="footer">
										<a href="#">View all</a>
									</li>
								</ul>
							</li><!-- Tasks Menu -->
							<li class="dropdown tasks-menu">
								<!-- Menu Toggle Button -->
								 <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-flag-o"></i> <span class="label label-danger">9</span></a>
								<ul class="dropdown-menu">
									<li class="header">You have 9 tasks</li>
									<li>
										<!-- Inner menu: contains the tasks -->
										<ul class="menu">
											<li>
												<!-- Task item -->
												 <a href="#"><!-- Task title and progress text -->
												<h3>Design some buttons <small class="pull-right">20%</small></h3><!-- The progress bar -->
												<div class="progress xs">
													<!-- Change the css width attribute to simulate progress -->
													<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" class="progress-bar progress-bar-aqua" role="progressbar" style="width: 20%">
														<span class="sr-only">20% Complete</span>
													</div>
												</div></a>
											</li><!-- end task item -->
										</ul>
									</li>
									<li class="footer">
										<a href="#">View all tasks</a>
									</li>
								</ul>
							</li><!-- User Account Menu -->
							<li class="dropdown user user-menu">
								<!-- Menu Toggle Button -->
								 <a class="dropdown-toggle" data-toggle="dropdown" href="#"><!-- The user image in the navbar-->
								 <i class="fa fa-fw fa-user"></i> 
								 <span class="hidden-xs"><%= render html: current_user.fullname.titleize rescue '-' %></span></a>
								<ul class="dropdown-menu">
									<!-- The user image in the menu -->	
									<li class="user-header">
										<h1><i class="fa fa-fw fa-user-circle" style="font-size:80px;color:white;"></i></h1>	
										<p><%= render html: current_user.fullname.titleize rescue '-' %> <small>Programmer</small></p>
									</li><!-- Menu Body -->
									<li class="user-body padding-xs">
										<div class="row ">
											<div class="col-xs-12 text-center ">
												<a style="font-weight: 600"><%= render html: current_user.branch.name.upcase rescue '-' %></a>
											</div>
										</div><!-- /.row -->
									</li><!-- Menu Footer-->
									<li class="user-footer">
										<div class="pull-left">
											<%= link_to raw("<i class=\"fa fa-user\" aria-hidden=\"true\"></i>&nbsp;&nbsp; Profile "), profile_path(current_user), class: "btn btn-default btns-flat" rescue '-' %>
										</div>
										<div class="pull-right">
											<%= link_to raw("<i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i> Sign out"), logout_path, method: :delete, :class => "btn btn-default btns-flat" %>
										</div>
									</li>
								</ul>
							</li><!-- Control Sidebar Toggle Button -->
							<li>
								<a data-toggle="control-sidebar" href="#"><i class="fa fa-gears"></i></a>
							</li>
						</ul>
					</div>
				</nav>
			</header>

app/views/layouts/partials/_sidebar.html.erb
			<aside class="main-sidebar">
				<!-- sidebar: style can be found in sidebar.less -->
				<section class="sidebar">
					<!-- Sidebar user panel (optional) -->
					<div class="user-panel">
						<div class="pull-left image">
							<h4><i class="fa fa-fw fa-user-circle" style="color:white;"></i></h4>
						</div>
						<div class="pull-left info">
							<p><%= render html: current_user.fullname.titleize rescue '-' %></p><!-- Status -->
							<a><i class="fa fa-circle text-success"></i> Online</a>
						</div>
					</div><!-- search form (Optional) -->
					<!-- Sidebar Menu -->
					<ul class="sidebar-menu" id="menu" style="font-size:14px !important">
						
						<li class="<%= 'active' if current_page?(pages_path) %>">
							<%= link_to "<i class='fa fa-dashboard text-white'></i> <span>Dashboard</span>".html_safe, pages_path , :rel => "tab" %></li>
						
						<li class="treeview <%= 'active' if params[:controller] == 'accounts' %><%= 'active' if params[:controller] == 'journals' %>">
							<%= link_to "<i class='fa fa-book text-white'></i> <span>General Ledger</span><span class='pull-right-container'><i class='fa fa-angle-left pull-right'></i></span>".html_safe, suppliers_path, :rel => "tab" %>
							<ul class="treeview-menu" style="font-size:14px !important">
								<li class="<%= 'active' if params[:controller] == 'accounts' %> ">
									<%= link_to "<i class='fa fa-caret-right '></i><i class='fa fa-pie-chart text-white'></i> <span>Chart of Accounts</span>".html_safe, accounts_path, :rel => "tab" %>
								</li>
								<li class="<%= 'active' if params[:controller] == 'journals' %>">
									<%= link_to "<i class='fa fa-caret-right '></i><i class='fa fa-calculator text-white'></i> <span>Journals</span>".html_safe, journals_path, :rel => "tab" %>
								</li>
							</ul>
						</li>
						
						<li class="<%= 'active' if params[:controller] == 'assetms' %>">
							<%= link_to "<i class='fa fa-car text-white'></i> <span>Assets</span>".html_safe,assetms_path, :rel => "tab" %></li>
							
						
						<li class="<%= 'active' if params[:controller] == 'customers' %>">
							<%= link_to "<i class='fa fa-smile-o'></i> <span>Customers</span>".html_safe, customers_path, :rel => "tab" %></li>
						
						<li class="<%= 'active' if params[:controller] == 'salesmen' %>">
							<%= link_to "<i class='fa fa-briefcase text-white'></i> <span>Salesmen</span>".html_safe, salesmen_path, :rel => "tab" %></li>
						
						<li class="<%= 'active' if params[:controller] == 'suppliers' %>">
							<%= link_to "<i class='fa fa-industry text-white'></i> <span>Suppliers</span>".html_safe, suppliers_path, :rel => "tab" %></li>
						
						<li class="treeview <%= 'active' if params[:controller] == 'product_settings' %><%= 'active' if params[:controller] == 'products' %><%= 'active' if params[:controller] == 'stocks' %>">
							<%= link_to "<i class='fa fa-cubes text-white'></i> <span>Inventories</span><span class='pull-right-container'><i class='fa fa-angle-left pull-right'></i></span>".html_safe, suppliers_path, :rel => "tab" %>
							<ul class="treeview-menu" style="font-size:14px !important">
								<li class="<%= 'active' if params[:controller] == 'stocks' %>">
									<%= link_to "<i class='fa fa-caret-right '></i><i class='fa fa-th text-white'></i> <span>Mutation Stocks</span>".html_safe, stocks_path, :rel => "tab" %>
								</li>
								<li class="<%= 'active' if params[:controller] == 'products' %>">
									<%= link_to "<i class='fa fa-caret-right '></i><i class='fa fa-cube text-white'></i> <span>Products</span>".html_safe, products_path, :rel => "tab" %>
								</li>
								<li class="<%= 'active' if params[:controller] == 'product_settings' %>">
									<%= link_to "<i class='fa fa-caret-right '></i><i class='fa fa-qrcode text-white'></i> <span>Product Settings</span>
										<span class='pull-right-container'>
						              		<small class='label pull-right bg-red'>admin</small>
						            	</span>".html_safe, product_settings_path, :rel => "tab" %>
								</li>
							</ul>
						</li>
						
						<li class="<%= 'active' if params[:controller] == 'users' %>">
							<%= link_to "<i class='fa fa-user text-white'></i> 
								<span>Users</span><span class='pull-right-container'>
				              		<small class='label pull-right bg-red'>admin</small>
				            	</span>".html_safe, users_path, :rel => "tab" %>
						</li>
						
						<li class="<%= 'active' if params[:controller] == 'branches' %>">
							<%= link_to "<i class='fa fa-database text-white'></i> <span>Branches</span>
								<span class='pull-right-container'>
				              		<small class='label pull-right bg-red'>admin</small>
				            	</span>".html_safe,branches_path, :rel => "tab" %></li>
							
						<li class="treeview">
							<a href="#"><i class="fa fa-link"></i> <span>Reports</span> <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
							<ul class="treeview-menu" style="font-size:14px !important">
								<li>
									<a href="#">Link in level 2</a>
								</li>
								<li>
									<a href="#">Link in level 2</a>
								</li>
							</ul>
						</li>
						
					</ul><!-- /.sidebar-menu -->
				</section><!-- /.sidebar -->
			</aside>